/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.fntech;

public final class R {
    public static Object raw;

    private R() {}

    public static final class array {
        private array() {}

        public static int P01SerialPort = 0x7f030001;
        public static int P01_GPIO = 0x7f030002;
        public static int m10ASerialPort = 0x7f030003;
        public static int m10A_GPIO = 0x7f030004;
        public static int m10SerialPort = 0x7f030005;
        public static int m10_GPIO = 0x7f030006;
        public static int m10_models = 0x7f030007;
        public static int m96SerialPort = 0x7f030008;
        public static int m96_GPIO = 0x7f030009;
        public static int m96_models = 0x7f03000a;
        public static int spinarr_baud = 0x7f03000b;
        public static int spinarr_model = 0x7f03000c;
        public static int spinarr_serialport = 0x7f03000d;
    }
    public static final class color {
        private color() {}

        public static int bottom_nav_normal = 0x7f060001;
        public static int bottom_nav_pressed = 0x7f060002;
    }
    public static final class dimen {
        private dimen() {}

        public static int activity_horizontal_margin = 0x7f080001;
        public static int activity_vertical_margin = 0x7f080002;
    }
    public static final class drawable {
        private drawable() {}

        public static int abc_btn_check_to_on_mtrl_000 = 0x7f090001;
        public static int abc_btn_check_to_on_mtrl_015 = 0x7f090002;
        public static int abc_btn_radio_to_on_mtrl_000 = 0x7f090003;
        public static int abc_btn_radio_to_on_mtrl_015 = 0x7f090004;
        public static int abc_checkbox = 0x7f090005;
        public static int abc_radio = 0x7f090006;
        public static int drawable_radiobutton_select = 0x7f090007;
        public static int ic_launcher = 0x7f090008;
        public static int ico_andriod = 0x7f090009;
        public static int ico_home = 0x7f09000a;
        public static int ico_menu = 0x7f09000b;
        public static int radiobutton_not_selected = 0x7f09000c;
        public static int radiobutton_selected = 0x7f09000d;
        public static int selector_ico_android = 0x7f09000e;
        public static int selector_ico_home = 0x7f09000f;
        public static int selector_ico_menu = 0x7f090010;
        public static int shape_ico_android_normal = 0x7f090011;
        public static int shape_ico_android_pressed = 0x7f090012;
        public static int shape_ico_home_normal = 0x7f090013;
        public static int shape_ico_home_pressed = 0x7f090014;
        public static int shape_ico_menu_normal = 0x7f090015;
        public static int shape_ico_menu_pressed = 0x7f090016;
    }
    public static final class id {
        private id() {}

        public static int baudRate_spinner = 0x7f0c0001;
        public static int bottom_nav_left = 0x7f0c0002;
        public static int bottom_nav_middle = 0x7f0c0003;
        public static int bottom_nav_right = 0x7f0c0004;
        public static int bottom_nav_right_menu = 0x7f0c0005;
        public static int bottom_nav_right_menu_item = 0x7f0c0006;
        public static int enableCheckBox = 0x7f0c0007;
        public static int model_spinner = 0x7f0c0008;
        public static int poweroff = 0x7f0c0009;
        public static int poweron = 0x7f0c000a;
        public static int relativeLayoutOFF_main = 0x7f0c000b;
        public static int relativeLayoutON_main = 0x7f0c000c;
        public static int saveBtn = 0x7f0c000d;
        public static int serialport_spinner = 0x7f0c000e;
        public static int textView_item = 0x7f0c000f;
    }
    public static final class layout {
        private layout() {}

        public static int activity_setandsave = 0x7f0f0001;
        public static int bottom_nav = 0x7f0f0002;
        public static int bottom_nav_right_menu = 0x7f0f0003;
        public static int bottom_nav_right_menu_item = 0x7f0f0004;
        public static int spinner_item = 0x7f0f0005;
    }
    public static final class string {
        private string() {}

        public static int action_settings = 0x7f150001;
        public static int app_name = 0x7f150002;
        public static int baudRate = 0x7f150003;
        public static int content_description = 0x7f150004;
        public static int enable = 0x7f150005;
        public static int hello_world = 0x7f150006;
        public static int model = 0x7f150007;
        public static int poweroff = 0x7f150008;
        public static int poweron = 0x7f150009;
        public static int rea_btn = 0x7f15000a;
        public static int serialport = 0x7f15000b;
        public static int str_btn = 0x7f15000c;
        public static int str_null = 0x7f15000d;
        public static int str_poweroff = 0x7f15000e;
        public static int str_poweron = 0x7f15000f;
    }
    public static final class style {
        private style() {}

        public static int AppBaseTheme = 0x7f160001;
        public static int AppTheme = 0x7f160002;
    }
}
